run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - gofumpt
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - errcheck
    - gocyclo
    - misspell
    - unconvert
    - whitespace
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  exclude-use-default: false
  max-same-issues: 50
  max-issues-per-linter: 50

output:
  formats:
    - format: colored-line-number
